### ISSUE TITLE
Certificate issues after login

### ISSUE THREAD

**Issue by Spirit-act** [TremoloSecurity/kubectl-login#15]
If I authenticate with `kubectl oulogin` after I applied the "kubectl Command" from the Dashboard, I get this message `Unable to connect to the server: x509: certificate signed by unknown authority`.

I have the same problem if I execute `kubectl oulogin --host=<k8s.example.com>`.

### My Setup
- Kubernetes version: v1.24.8
- Service Mesh / Ingress: Istio v.1.16.0
- OIDC Provider: AzureAD
- I use a own (trusted) wildcard Cert

### Debug Infos

The Login Portal and Dashboards work just fine, but the API has still a self signed cert. I followed [This Tutorial](https://openunison.github.io/knowledgebase/certificates/#how-do-i-change-openunisons-certificates).

The output of `openssl s_client -showcerts -connect api.example.com:443 </dev/null` looks like this:

```
CONNECTED(00000003)
depth=0 CN = openunison-orchestra.openunison.svc, OU = Kubernetes, O = MyOrg, L = My Cluster, ST = State of Cluster, C = MyCountry
verify error:num=18:self-signed certificate
verify return:1
depth=0 CN = openunison-orchestra.openunison.svc, OU = Kubernetes, O = MyOrg, L = My Cluster, ST = State of Cluster, C = MyCountry
verify error:num=26:unsupported certificate purpose
verify return:1
depth=0 CN = openunison-orchestra.openunison.svc, OU = Kubernetes, O = MyOrg, L = My Cluster, ST = State of Cluster, C = MyCountry
verify return:1
---
Certificate chain
 0 s:CN = openunison-orchestra.openunison.svc, OU = Kubernetes, O = MyOrg, L = My Cluster, ST = State of Cluster, C = MyCountry
   i:CN = openunison-orchestra.openunison.svc, OU = Kubernetes, O = MyOrg, L = My Cluster, ST = State of Cluster, C = MyCountry
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Dec  2 13:00:06 2022 GMT; NotAfter: Dec  2 13:00:06 2023 GMT
-----BEGIN CERTIFICATE-----
MIIEFzCCAv+gAwIBAgIGAYTS7DZaMA0GCSqGSIb3DQEBCwUAMIGXMSwwKgYDVQQD...
-----END CERTIFICATE-----
---
Server certificate
subject=CN = openunison-orchestra.openunison.svc, OU = Kubernetes, O = MyOrg, L = My Cluster, ST = State of Cluster, C = MyCountry
issuer=CN = openunison-orchestra.openunison.svc, OU = Kubernetes, O = MyOrg, L = My Cluster, ST = State of Cluster, C = MyCountry
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1591 bytes and written 385 bytes
Verification error: unsupported certificate purpose
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 26 (unsupported certificate purpose)
....
```

I can workaround this issue if i add the `certificate-authority-data`  or `insecure-skip-tls-verify: true` to the cluster map within the kubeconfig. I need to do this every time I need to reauthenticate with `kubectl oulogin` and this is not very practical.

### Question

Would it be possible to add, that the ca-data is also written in the cluster config, like in the "kubectl command"?

---

I was not sure where to open this issue, because I see it on one site as a certificate issue and on the other site as a kubectl plugin issue. If you think this is only a certificate issue, I will open an issue in the [helm chart repo](https://github.com/OpenUnison/helm-charts).

Thank you in advance.

**Comment by mlbiam** [comment]
hmm, it should be including the internal cert with Istio (we bypass TLS termination with impersonation and Istio because envoy doesn't support SPDY with TLS termination).  When you use the portal --> Get Tokens method, is the certificate embedded as expected?

I'll see if I can reproduce locally.

**Comment by mlbiam** [comment]
Another question, did you follow https://openunison.github.io/knowledgebase/certificates/, adding your wildcard's CA as an entry in `trusted_certs` with the name `unison-ca`?

**Comment by mlbiam** [comment]
So there was a bug in the chart used to support oulogin (but not the token generation screen).  That's fixed so `helm repo update` and `helm upgrade orchestra-login-portal tremolo/orchestra-login-portal -n openunison -f /path/to/values.yaml` should get that updated.  Also updated the Istio configuration - https://openunison.github.io/ingresses/istio/#deployment

**Comment by Spirit-act** [comment]
Thanks for the fast response.

With your fix the `certificate-authority-data` is correctly written into the kubeconfig.

The used TLS Cert is a one-year valid cert from Sentigo. Do I still need to add it to the `trusted_certs`, just to be on the safe side?

**Comment by mlbiam** [comment]
> The used TLS Cert is a one-year valid cert from Sentigo. Do I still need to add it to the trusted_certs, just to be on the safe side?

probably not.  You can skip adding `unison-ca` to `trusted_certs` and also set `impersonation.explicit_certificate_trust=false` in your values.yaml so your kube-oidc-proxy will use ubuntu's cert store

**Comment by Spirit-act** [comment]
As far as I see `impersonation.explicit_certificate_trust=false` is not required, so I will stick with the default option.

Thanks for your quick help.
