### ISSUE TITLE
Installing the plugin in an air gap network

### ISSUE THREAD

**Issue by jashykm** [TremoloSecurity/kubectl-login#4]
How can I install this plugin in an air gap network?

**Comment by mlbiam** [comment]
https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/oulogin.yaml lists the urls for each of the supported platforms.  Download the appropriate zip file for your platform, unzip it and place it in the system's PATH

**Comment by jashykm** [comment]
Thank you.
